// dart format width=80
// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'aes_auth_encrypt_infos.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

// dart format off
T _$identity<T>(T value) => value;
/// @nodoc
mixin _$AesAuthEncryptInfos {

/// The authentication tag (e.g., MAC) generated by the authenticated encryption mode (like AES-GCM).
/// This is used to verify the integrity and authenticity of the encrypted data.
@Uint8ListConverter() Uint8List? get tag;/// The encrypted data (ciphertext).
@Uint8ListConverter() Uint8List? get encrypted;
/// Create a copy of AesAuthEncryptInfos
/// with the given fields replaced by the non-null parameter values.
@JsonKey(includeFromJson: false, includeToJson: false)
@pragma('vm:prefer-inline')
$AesAuthEncryptInfosCopyWith<AesAuthEncryptInfos> get copyWith => _$AesAuthEncryptInfosCopyWithImpl<AesAuthEncryptInfos>(this as AesAuthEncryptInfos, _$identity);



@override
bool operator ==(Object other) {
  return identical(this, other) || (other.runtimeType == runtimeType&&other is AesAuthEncryptInfos&&const DeepCollectionEquality().equals(other.tag, tag)&&const DeepCollectionEquality().equals(other.encrypted, encrypted));
}


@override
int get hashCode => Object.hash(runtimeType,const DeepCollectionEquality().hash(tag),const DeepCollectionEquality().hash(encrypted));

@override
String toString() {
  return 'AesAuthEncryptInfos(tag: $tag, encrypted: $encrypted)';
}


}

/// @nodoc
abstract mixin class $AesAuthEncryptInfosCopyWith<$Res>  {
  factory $AesAuthEncryptInfosCopyWith(AesAuthEncryptInfos value, $Res Function(AesAuthEncryptInfos) _then) = _$AesAuthEncryptInfosCopyWithImpl;
@useResult
$Res call({
@Uint8ListConverter() Uint8List? tag,@Uint8ListConverter() Uint8List? encrypted
});




}
/// @nodoc
class _$AesAuthEncryptInfosCopyWithImpl<$Res>
    implements $AesAuthEncryptInfosCopyWith<$Res> {
  _$AesAuthEncryptInfosCopyWithImpl(this._self, this._then);

  final AesAuthEncryptInfos _self;
  final $Res Function(AesAuthEncryptInfos) _then;

/// Create a copy of AesAuthEncryptInfos
/// with the given fields replaced by the non-null parameter values.
@pragma('vm:prefer-inline') @override $Res call({Object? tag = freezed,Object? encrypted = freezed,}) {
  return _then(_self.copyWith(
tag: freezed == tag ? _self.tag : tag // ignore: cast_nullable_to_non_nullable
as Uint8List?,encrypted: freezed == encrypted ? _self.encrypted : encrypted // ignore: cast_nullable_to_non_nullable
as Uint8List?,
  ));
}

}


/// @nodoc


class _AesAuthEncryptInfos extends AesAuthEncryptInfos {
  const _AesAuthEncryptInfos({@Uint8ListConverter() this.tag, @Uint8ListConverter() this.encrypted}): super._();
  

/// The authentication tag (e.g., MAC) generated by the authenticated encryption mode (like AES-GCM).
/// This is used to verify the integrity and authenticity of the encrypted data.
@override@Uint8ListConverter() final  Uint8List? tag;
/// The encrypted data (ciphertext).
@override@Uint8ListConverter() final  Uint8List? encrypted;

/// Create a copy of AesAuthEncryptInfos
/// with the given fields replaced by the non-null parameter values.
@override @JsonKey(includeFromJson: false, includeToJson: false)
@pragma('vm:prefer-inline')
_$AesAuthEncryptInfosCopyWith<_AesAuthEncryptInfos> get copyWith => __$AesAuthEncryptInfosCopyWithImpl<_AesAuthEncryptInfos>(this, _$identity);



@override
bool operator ==(Object other) {
  return identical(this, other) || (other.runtimeType == runtimeType&&other is _AesAuthEncryptInfos&&const DeepCollectionEquality().equals(other.tag, tag)&&const DeepCollectionEquality().equals(other.encrypted, encrypted));
}


@override
int get hashCode => Object.hash(runtimeType,const DeepCollectionEquality().hash(tag),const DeepCollectionEquality().hash(encrypted));

@override
String toString() {
  return 'AesAuthEncryptInfos(tag: $tag, encrypted: $encrypted)';
}


}

/// @nodoc
abstract mixin class _$AesAuthEncryptInfosCopyWith<$Res> implements $AesAuthEncryptInfosCopyWith<$Res> {
  factory _$AesAuthEncryptInfosCopyWith(_AesAuthEncryptInfos value, $Res Function(_AesAuthEncryptInfos) _then) = __$AesAuthEncryptInfosCopyWithImpl;
@override @useResult
$Res call({
@Uint8ListConverter() Uint8List? tag,@Uint8ListConverter() Uint8List? encrypted
});




}
/// @nodoc
class __$AesAuthEncryptInfosCopyWithImpl<$Res>
    implements _$AesAuthEncryptInfosCopyWith<$Res> {
  __$AesAuthEncryptInfosCopyWithImpl(this._self, this._then);

  final _AesAuthEncryptInfos _self;
  final $Res Function(_AesAuthEncryptInfos) _then;

/// Create a copy of AesAuthEncryptInfos
/// with the given fields replaced by the non-null parameter values.
@override @pragma('vm:prefer-inline') $Res call({Object? tag = freezed,Object? encrypted = freezed,}) {
  return _then(_AesAuthEncryptInfos(
tag: freezed == tag ? _self.tag : tag // ignore: cast_nullable_to_non_nullable
as Uint8List?,encrypted: freezed == encrypted ? _self.encrypted : encrypted // ignore: cast_nullable_to_non_nullable
as Uint8List?,
  ));
}


}

// dart format on
