import 'dart:typed_data';

import 'package:archethic_lib_dart/src/utils/uint8List_converter.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'aes_auth_encrypt_infos.freezed.dart';

/// Represents the output of an authenticated AES encryption operation.
///
/// It typically includes the encrypted data and an authentication tag.
@freezed
abstract class AesAuthEncryptInfos with _$AesAuthEncryptInfos {
  /// Creates an [AesAuthEncryptInfos] instance.
  ///
  /// The [tag] is the authentication tag generated during encryption.
  /// The [encrypted] is the ciphertext.
  const factory AesAuthEncryptInfos({
    /// The authentication tag (e.g., MAC) generated by the authenticated encryption mode (like AES-GCM).
    /// This is used to verify the integrity and authenticity of the encrypted data.
    @Uint8ListConverter() final Uint8List? tag,

    /// The encrypted data (ciphertext).
    @Uint8ListConverter() final Uint8List? encrypted,
  }) = _AesAuthEncryptInfos;

  /// Private constructor for [AesAuthEncryptInfos].
  const AesAuthEncryptInfos._();
}
